### ISSUE TITLE
Syntax error with time in exponential notation

### ISSUE THREAD

**Issue by cmarqu** [chipsalliance/verible#1224]
Using current `master` (verible-v0.0-1959-gd9b88c73).

**Test case**

```systemverilog
$realtime/1.0e-9s
```

**Actual output**

```
syntax error, rejected "s" (syntax-error).
```

It works with

```systemverilog
$realtime/0.000000001s
```

**Comment by rfdonnelly** [comment]
Verible looks to be doing the right thing here.  SystemVerilog time literals can't have exponents.  Here is the BNF from 1800-2017:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/28975/160260188-f2c6c020-7361-4780-9b83-11199cad3a69.png">

<img width="315" alt="image" src="https://user-images.githubusercontent.com/28975/160260112-437893d9-c99a-4a07-8122-5f14a0469d5e.png">

Note that the BNF for `time_literal` does not include `real_number`.

To make your test case valid SystemVerilog, you could rewrite as `$realtime/1.0e-9*1.0s`
