### ISSUE TITLE
Smoke test expected failures might need to be updated

### ISSUE THREAD

**Issue by karimtera** [chipsalliance/verible#1306]
Hello, 

While working on [PR#1297](https://github.com/chipsalliance/verible/pull/1297), my latest commit didn't pass the smoke test.
I got confused as i only did some changes in help comments, and markdown documents.

Trials:

1. Pulled changes from the master branch, failed the smoke test.
2. Checked-out to master branch (maybe i messed up my branch), still failed the smoke test.

Note: I run the tests locally, maybe something wrong in my environment?

Fix Proposed:
Change expected failures of project `opentitan` to `648` instead of `646`

I will gladly do it, once it is confirmed as a real issue.

**Comment by hzeller** [comment]
we're pulling the 'live' repositories we're running the tools against, so it might well be that the number of failures change.
Let me fix that quickly.

**Comment by hzeller** [comment]
Alright, done. Rebase and try again.
