### ISSUE TITLE
Smoke test update expected failures

### ISSUE THREAD

**Issue by karimtera** [chipsalliance/verible#1308]
Hello, 

I am facing the same issue as [#1306](https://github.com/chipsalliance/verible/issues/1306).

Needed fixes:
- `project:ibex`: 173 instead of 172
- `syntax:opentitan`: 28 instead of 27
- `lint:opentitan`: 28 instead of 27
- `project:opentitan`: 650 instead of 648

**Comment by hzeller** [comment]
Fixed with #1311 that also adds a little bit of padding to the expected failure numbers.
