### ISSUE TITLE
auto-expand code-action shown for every line

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/verible#1741]
A couple of questions first

 - Your IDE/editor (e.g. vscode, emacs,...) you use with verible LSP ? vscode
-----

With the auto-expand option enabled, the code action offering (the little ':bulb:' in vscode) shows for every line.
This is somewhat distracting to the user (and also it apparently requires the auto-expand to re-evaluate everything on every cursor move.)

**Expectation**

The code action should only show up in a line in which an actual `AUTO*` comment is residing.

Ideally, it should offer two code-actions to choose from: 'only expand this instance', 'expand all auto comments in the same file' (maybe also 'expand all fromt he same kind' ? e.g.  if I am in a line with AUTOINST, only expand other AUTOINST in the rest of the file).

Advantage: less distraction for the user, and potentially cheaper to calculate for the language server if it knows where the cursor is.

**Comment by kbieganski** [comment]
> it apparently requires the auto-expand to re-evaluate everything on every cursor move

In the future we'll want to change this to what code actions in other language servers usually do: the code action only returns a command identifier, and then if the user selects that code action, the command is ran and all the heavy lifting happens.
