### ISSUE TITLE
crashes on $finish and $fatal

### ISSUE THREAD

**Issue by jjts** [chipsalliance/verible#1914]
if(!failed) begin
      $fwrite(fd, "Test passed!\n");
      $finish;
    end else begin
      $fatal(1, "Test failed!");
    end
  end

**Comment by hzeller** [comment]
If this is within a valid outer construct, such as a a module, 

```systemverilog
module foo ();
  if (!failed) begin
    $fwrite(fd, "Test passed!\n");
    $finish;
  end else begin
    $fatal(1, "Test failed!");
  end
endmodule
```

It will not bail out with a syntax error.

However, the formatted output still adds seemingly unnecessary newlines. And misses a newline before the `$finish;` @jbylicki can you have a look ?

```systemverilog
module foo ();
  if (!failed) begin
    $fwrite(
        fd, "Test passed!\n"
    ); $finish;
  end else begin
    $fatal(
        1, "Test failed!"
    );
  end
endmodule
```

**Comment by jjts** [comment]
It does crash. But not in a small example than the above. I worked around it by doing 
....
end else begin
   $display("Test failed!");
    $fatal(1);
  end
