### ISSUE TITLE
Ugly output for type declarations with macro + argument

### ISSUE THREAD

**Issue by nathanbeckmann** [chipsalliance/verible#1924]
**Test case**

A type declaration like the following:

```
    logic [WIDTH-1:0] data[
    `NONNEGATIVE(COUNT-1)
    :0];
```

gets formatted with newlines. (Until recently, this crashed -- thanks for fixing that!) I would prefer:

```
    logic [WIDTH-1:0] data[`NONNEGATIVE(COUNT-1):0];
```

Is there an option to control this that I have missed?

**Comment by hzeller** [comment]
@jbylicki I think you're working on something like this right now ?

**Comment by jbylicki** [comment]
Yes, #1917 should've addressed this but it did not fix that case, I will take a look at it
