### ISSUE TITLE
Any plans to add CDC linting?

### ISSUE THREAD

**Issue by chili-chips-ba** [chipsalliance/verible#2216]
With majority of opensource RTL developers being converted software engineers, a CDC validation tool would greatly help improve the quality of IP in opensource domain.

**Comment by corco** [comment]
No, this is out of scope for something like Verible. To do CDC, you must elaborate the design, which is not done by Verible.

You may look at tools like [YosysHQ](https://www.yosyshq.com/) or [slang](https://sv-lang.com/), which do design elaboration.
