### ISSUE TITLE
Lint rule [instance-shadowing] raising violations on modport entries

### ISSUE THREAD

**Issue by sconwayaus** [chipsalliance/verible#2248]
**Describe the bug**
Lint rule 'instance-shadowing' is not handling interfaces well, rasising vilations on modport items shadowing interface signals.

**Test case (preferably reduced)**
```systemverilog
// Ran the style linter on this code.
interface rconst_interface;
    logic [23:0] i;
    logic [63:0] rc;

    modport slave (
        input i,    // Violation raised here for 'i'
        output rc    // Violation raised here for 'rc'
    );
endinterface

```
**Actual vs. expected behavior**
False positive violations are raised
Symbol `i` is shadowing symbol `i` defined at @ [Style: mark-shadowed-instances][instance-shadowing]
Symbol `rc` is shadowing symbol `rc` defined at @ [Style: mark-shadowed-instances][instance-shadowing]

Tested on verible-v0.0-3756-gda9a0f8c

**Comment by IEncinas10** [comment]
I took a look at this. I guess the best solution is to ignore declarations inside modports given that they are not actually shadowing anything, right? 

Let me know if you're planning on opening a PR

**Comment by sconwayaus** [comment]
Thanks. I took a look at this a few days ago and like you said, it was just
a matter of  ignoring symbols in modports. I'll push something across
shortly.
