### ISSUE TITLE
CI stuck on spinning up self-hosted runners

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/verible#2296]
Did I overwhelm the runners, or is there some configuration issue somewhere ?

Link to current stuck CI https://github.com/chipsalliance/verible/actions/runs/11991068681/job/33429240316 .. but it also started doing that a couple of pushes ago on Friday.

Assigning to @kgugala as he is/might know the best person to figure out what is causing this.

**Comment by kgugala** [comment]
This is fixed now - I see queued jobs were picked up. It may take some time to process the backlog, but the CI is up and running.
