### ISSUE TITLE
 [fixer, undersized-binary-literal] suggest the minimum size evaluated/inferred

### ISSUE THREAD

**Issue by msfschaffner** [chipsalliance/verible#314]
Cloned from internal tracking on behalf of @fangism:

The diagnostic message for this rule already shows the actual and required literal width, so why not just take the actual width and make a suggested-fix out of it?

It is possible that the correct fix should be wider, but that should be left up to the user to discern.

**Comment by msfschaffner** [comment]
b/157431880

**Comment by fangism** [comment]
Prerequisite: #284
