### ISSUE TITLE
 [fixer, no-trailing-spaces] just delete it, like the formatter

### ISSUE THREAD

**Issue by msfschaffner** [chipsalliance/verible#315]
Cloned from internal tracking on behalf of @fangism:

Even though whitespace management is the domain of the formatter, we have a lint rule that checks for trailing spaces that predates the formatter. Nevertheless this would be a good task to demonstrate the suggest-fix workflow, for pipecleaning.

**Comment by msfschaffner** [comment]
b/157430954

**Comment by fangism** [comment]
Prerequisite: #284

**Comment by IEncinas10** [comment]
This was fixed here https://github.com/chipsalliance/verible/commit/13365dbd511dba643c03c5be7ab33708d40791b6
