### ISSUE TITLE
Support building with glibc 2.34

### ISSUE THREAD

**Issue by imphil** [chipsalliance/verible#957]
glibc 2.34, which is currently being rolled out in first distributions, has broken some vendored dependencies of Verible. Let's use this as a tracking issue to update them.

* [ ] m4 doesn't build. Dependency update not yet available. Filed https://github.com/jmillikin/rules_m4/issues/9
* [x] absl doesn't build. Dependency update: https://github.com/chipsalliance/verible/pull/956

(There might be more, but that's currently where I'm stuck.)

**Comment by hzeller** [comment]
If we send a pull request to the https://github.com/jmillikin/rules_m4 project, we have more under control when things happen. Tom, could you check if this something we can do ?
